### ISSUE TITLE
Dimensions have many significant digits.

### ISSUE THREAD

**Issue by workergnome** [american-art/wam#17]
If I look at, say, [This dimension](http://data.americanartcollaborative.org/page/wam/object/id/9895/physical/overall/dimension/id/26862/value/diameter), there are a huge number of significant digits:  `rdf:value: 1.4000000000`

Is this by intent, @kateblanch?  I don't want to truncate this if it's meaningful, but I also don't know that you're actually measuring down to the atomic level, either.

**Comment by kateblanch** [comment]
Please truncate! Truncate away, we only measure to the tenth (.X) - it is the source system that stores it so finely.

**Comment by workergnome** [comment]
ISI folk, can we do this in the mapping?  I'm nervous to change data in the browse application, since other institutions may use significant digits to indicate real information.

**Comment by caknoblock** [comment]
Yes, we can truncate the extra digits in the mapping process.
Craig

**Comment by bsnikhila** [comment]
I modified it. I rounded up the values, not truncated. Let me know if that is an issue and you want me to truncate it only.

**Comment by workergnome** [comment]
As long as rounding doesn't change any of the values, that's probably fine—I wouldn't want the numbers to be different—I just want the trailing zeroes to be gone.

**Comment by kateblanch** [comment]
Please only truncate to the 2nd decimal place. Rounding up is not the right approach, because the measurement is actually taken to the tenth decimal place. 
24.1000000000 CM truncate to 24.1 CM

You will have to round to the tenth decimal place.
40.640081280 CM round and/or truncate to 40.6 CM

Hope that helps to clarify. Let me know if more info is needed. Thanks for being so thorough on this!

**Comment by bsnikhila** [comment]
Alright, I changed it
